<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>manejo de errores</title>
    <script>

        const myPost = {
            title: 'un post de hechos reales',
            body: '42',
            userId: 2
        }


        const opciones = {
            method: 'POST',
            body: JSON.stringify(myPost),
            headers: {
                'Content-Type': 'application/json'
            }
        };




        fetch('https://jsonplaceholder.typicode.com/postsZZZ', opciones)
            .then(res => {
                if (res.ok) {
                    return res.json();
                } else {
                    return Promise.reject({ status: res.status, statusText: res.statusText });
                }
            })
            .then(res => console.log(res))
            .catch(err => console.log('Error, con la siguiente anotaci√≥n:', err.statusText));
    </script>
</head>

<body>

</body>

</html>